FROM centos:6.8

# Run updates
RUN yum -y install epel-release
RUN yum update -y

### Install ansible
# Install python prerequisites
RUN yum -y install ansible

# Create ansible inventory file
RUN mkdir -p /etc/ansible
RUN echo "localhost ansible_connection=local" > /etc/ansible/hosts
